# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUrXXri69rU-U1SaGF1iCf6u1cfvLYXH
"""

#ejemplo de un codigo#
notas=[[10,20,30],[40, 37, 100],[75,80,90]]
print (notas)